# image: 'rust:latest'
image: 'clux/muslrust:stable'

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

# Cache is unusable currently:
# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1797
#
# cache:
#   paths:
#     - apt/
#     - cargo/
#     - target/

stages:
  - check
  - test
  - build-musl
  - doc

check:
  stage: check
  script:
    - rustc --version
    - cargo --version
    - cargo check --verbose
  only:
    - main
    - tags

test:
  stage: test
  script:
    - cargo test --verbose
  only:
    - main
    - tags

build-musl:
  stage: build-musl
  artifacts:
    name: "lowrr-executables"
    paths:
      - 'target/x86_64-unknown-linux-musl/release/lowrr'
      - 'target/x86_64-unknown-linux-musl/release/warp-crop'
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  only:
    - main
    - tags

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=lowrr">' > public/index.html
  artifacts:
    name: "doc"
    paths:
      - public
  only:
    - main
    - tags
